export default [
  { src: "img/1.webp", alt: "img1" },
  { src: "img/2.webp", alt: "img2" },
  { src: "img/3.webp", alt: "img3" },
  { src: "img/4.webp", alt: "img4" },
  { src: "img/5.webp", alt: "img5" },
  { src: "img/6.webp", alt: "img6" },
  { src: "img/7.webp", alt: "img7" },
  { src: "img/8.webp", alt: "img8" },
  { src: "img/9.webp", alt: "img9" },
  { src: "img/10.webp", alt: "img10" },
  { src: "img/11.webp", alt: "img11" },
  { src: "img/12.webp", alt: "img12" },
  { src: "img/13.webp", alt: "img13" },
  { src: "img/14.webp", alt: "img14" },
  { src: "img/15.webp", alt: "img15" },
  { src: "img/16.webp", alt: "img16" },
  { src: "img/17.webp", alt: "img17" },
  { src: "img/18.webp", alt: "img18" },
  { src: "img/19.webp", alt: "img19" },
  { src: "img/20.webp", alt: "img20" },
  { src: "img/21.webp", alt: "img21" },
  { src: "img/22.webp", alt: "img22" },
];
