name: cd
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build assets
        run: npm run export
      - name: Delete everything but the '__sapper__' directory
        run: |
          find . -type f -maxdepth 1 -exec rm -f {} +
          find . ! \( -name '.' -o -name '..' -o -name '.git' -o -name '__sapper__' \) -type d -maxdepth 1 -exec rm -rf {} +
      - name: Move the '__sapper__/export' directory contents up to the root
        run: |
          mv __sapper__/export/* .
          rm -rf __sapper__
      - name: Configure git
        run: |
          git config --local user.email "dakota.lillie@icloud.com"
          git config --local user.name "Dakota Lillie"
      - name: Commit changes
        run: |
          git switch -c production
          git add .
          git commit -m "Production deployment"
      - name: Push to production
        run: git push --force origin production