name: cd
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Delete everything but the 'build' directory
        run: |
          find . -type f -maxdepth 1 -exec rm -f {} +
          find . ! \( -name '.' -o -name '..' -o -name '.git' -o -name 'build' \) -type d -maxdepth 1 -exec rm -rf {} +
      - name: Move the 'build' directory contents up to the root
        run: |
          mv build/* .
          rm -rf build
      - name: Create CNAME file
        run: |
          echo "www.laurensettembrino.com" > CNAME
      - name: Create nojekyll file
        run: touch .nojekyll
      - name: Configure git
        run: |
          git config --local user.email "dakota.lillie@icloud.com"
          git config --local user.name "Dakota Lillie"
      - name: Commit changes
        run: |
          git switch -c production
          git add .
          git commit -m "Production deployment"
      - name: Push to production
        run: git push --force origin production
